Support encrypt with ES & CVM data disks, support authorization with TKE
tencentcloudstack/terraform-provider-tencentcloud pull request #521
Opened 2020-09-24 07:12 UTC by gailwang

ES test

```
make testacc TESTARGS=" -run=TestAccTencentCloudElasticsearchInstance"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudElasticsearchInstance -timeout 120m
?       github.com/tencentcloudstack/terraform-provider-tencentcloud    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc    (cached) [no tests to run]
=== RUN   TestAccTencentCloudElasticsearchInstancesDataSource
=== PAUSE TestAccTencentCloudElasticsearchInstancesDataSource
=== RUN   TestAccTencentCloudElasticsearchInstance
=== PAUSE TestAccTencentCloudElasticsearchInstance
=== CONT  TestAccTencentCloudElasticsearchInstancesDataSource
=== CONT  TestAccTencentCloudElasticsearchInstance
--- PASS: TestAccTencentCloudElasticsearchInstancesDataSource (645.40s)
--- PASS: TestAccTencentCloudElasticsearchInstance (1132.66s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       1133.953s
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity  [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper       [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/ratelimit     [no test files]

```

TKE tests
```
make testacc TESTARGS=" -run=TestAccTencentCloudTkeResource"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudTkeResource -timeout 120m
?       github.com/tencentcloudstack/terraform-provider-tencentcloud    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc     (cached) [no tests to run]
=== RUN   TestAccTencentCloudTkeResource
--- PASS: TestAccTencentCloudTkeResource (239.99s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       241.195s
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity  [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper       [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/ratelimit     [no test files]

```

CVM tests
```
  make testacc TESTARGS=" -run=TestAccTencentCloudInstanceWithDataDisk"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudInstanceWithDataDisk -timeout 120m
?       github.com/tencentcloudstack/terraform-provider-tencentcloud    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc    (cached) [no tests to run]
=== RUN   TestAccTencentCloudInstanceWithDataDisk
=== PAUSE TestAccTencentCloudInstanceWithDataDisk
=== CONT  TestAccTencentCloudInstanceWithDataDisk
--- PASS: TestAccTencentCloudInstanceWithDataDisk (65.58s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       66.876s
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity  [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper       [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/ratelimit     [no test files]
```

2020-09-24 07:38 UTC, longkai requested changes
hcl的注释里也格式化一下吧

2020-09-24 07:38 UTC, longkai commented on tencentcloud/resource_tc_elasticsearch_instance.go
> +	encrypt = false
这里格式化一下更好吧？

2020-09-24 07:38 UTC, longkai commented on tencentcloud/resource_tc_instance.go
> +	encrypt = false
格式化

2020-09-24 07:38 UTC, longkai commented on tencentcloud/resource_tc_instance_test.go
> +	encrypt = true
格式化

2020-09-24 07:38 UTC, longkai commented on tencentcloud/resource_tc_kubernetes_cluster.go
> +	cam_role_name			  = "CVM_QcsRole"
格式化

2020-09-24 07:38 UTC, longkai commented on tencentcloud/resource_tc_kubernetes_cluster_test.go
> +	cam_role_name			= "CVM_QcsRole"
格式化

2020-09-24 07:40 UTC, longkai approved these changes

2020-09-24 14:59 UTC, oliverpei commented on tencentcloud/resource_tc_elasticsearch_instance_test.go
> +			/*{
导入需要测试

2020-09-25 03:47 UTC, gailwang commented
```
make testacc TESTARGS=" -run=TestAccTencentCloudElasticsearchInstance_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudElasticsearchInstance_ -timeout 120m
?       github.com/tencentcloudstack/terraform-provider-tencentcloud    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc     (cached) [no tests to run]
=== RUN   TestAccTencentCloudElasticsearchInstance_basic
=== PAUSE TestAccTencentCloudElasticsearchInstance_basic
=== CONT  TestAccTencentCloudElasticsearchInstance_basic
--- PASS: TestAccTencentCloudElasticsearchInstance_basic (944.09s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       945.327s
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity  [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper       [no test files]
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/ratelimit     [no test files]

```

2020-09-25 04:03 UTC, oliverpei approved these changes

2020-09-25 04:03 UTC, merged